service: contact-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  memorySize: 256
  timeout: 10

IAMRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:PutItem"
      - "dynamodb:GetItem"
      - "dynamodb:UpdateItem"
      - "dynamodb:DeleteItem"
      - "dynamodb:Scan"
    Resource:
      - "arn:aws:dynamodb:us-west-2:*:table/ContactsTable"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /api/contacts
          method: any
          cors: true
      - http:
          path: /api/contacts/*
          method: any
          cors: true