service: contact-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  memorySize: 256
  timeout: 10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "s3:ListBucket"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:dynamodb:us-west-2:*:table/ContactsTable"

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /api/contacts/*
          method: any
          cors: true
      - https:
          path: /api/contacts/*
          method: any
          cors: true